### ISSUE TITLE
Make Kings Corner

### ISSUE THREAD

**Issue by gcwatts** [rjwoods/CSC495-Group-Q#1]
Making this issue for notes on what needs to be done
-Player.play isn't working currently, not sure if I should make deck into my own class with a method for removing a card from the middle of a list or not
-Wrote up to the start of a players turn

**Comment by rjwoods** [comment]
Bartok:
1. Debug Ace wild card
2. Implement Timer (last priority)

Kings Corner:
1. Debug play functions, and give them checking for valid plays

Everything:
1. Clean all the files
2. Record people playing the game
